name: api production

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clean artifact cache
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: 'ubuntu@140.238.219.21'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          rm -rf ./monorepo
    - name: Deploy artifact to host
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        username: 'ubuntu'
        server: '140.238.219.21'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: '.'
        remote_path: '/home/ubuntu/monorepo/'
        args: '-o ConnectTimeout=5'
    - name: Install dependencies
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: 'ubuntu@140.238.219.21'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          cd ./monorepo
          npm ci
    - name: Bootstrap application
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: 'ubuntu@140.238.219.21'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          cd ./monorepo
          npm run build
    - name: Copy SSL secrets into application folder
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: 'ubuntu@140.238.219.21'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          cp -r ./secrets ./monorepo/packages/secrets
    - name: Run builded api application in pm2 daemon
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: 'ubuntu@140.238.219.21'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          cd ./monorepo/packages/api
          pm2 start ecosystem.config.js