name: api production

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
        npm-version: [7]
    if: "contains(github.event.head_commit.message, 'api:')"
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Update npm ${{ matrix.npm-version }}
      run: npm install -g npm@${{ matrix.npm-version }}
    - name: Aga
      run: |
        node --version
        npm --version
    - name: Install dependencies
      run: npm ci
    - name: Bootstrap and Build application
      run: npm run build:api
    - name: Prepare cloud instance for artifact upload
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: 'ubuntu@140.238.219.21'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          rm -rf ./pawcapsu
    - name: Prepare artifact before cloud push
      run: |
        cp packages/api/package.json packages/api/dist
        cp packages/api/package-lock.json packages/api/dist
        cp packages/api/ecosystem.config.js packages/api/dist
    - name: Push artifact code to cloud
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        username: 'ubuntu'
        server: '140.238.219.21'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './packages/api/dist'
        remote_path: '/home/ubuntu/pawcapsu/'
        args: '-o ConnectTimeout=5'
    - name: Install dependencies on cloud server
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: 'ubuntu@140.238.219.21'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          cd ./pawcapsu
          npm ci
    - name: Start application in pm2 daemon
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: 'ubuntu@140.238.219.21'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          cd ./pawcapsu
          pm2 start ecosystem.config.js