name: api production

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy application artifact to host
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        username: 'ubuntu'
        server: '140.238.219.21'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './packages/*'
        remote_path: '/home/ubuntu/monorepo/'
    - name: Bootstrap application
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: 'ubuntu@140.238.219.21'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          cd ./monorepo
          npm run build
    - name: Run deployed artifact in pm2 daemon
      uses: JimCronqvist/action-ssh@0.1.1
      with:
        hosts: 'ubuntu@140.238.219.21'
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        command: |
          cd ./monorepo
          pm2 start ecosystem.config.js