name: pawcapsu/notifier production

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
        npm-version: [7]
    if: "contains(github.event.head_commit.message, 'api:')"
    steps:
    - uses: actions/checkout@v2
    - name: Use node@${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use npm@${{ matrix.npm-version }}
      run: npm install -g npm@${{ matrix.npm-version }}
    - name: Install dependencies
      run: npm ci
    - name: Bootstrap and Build application
      run: npm run build:notifier
    - name: Prepare artifact before cloud push
      run: |
        cp backend/notifier/package.json backend/notifier/dist
        cp backend/notifier/captain-definition backend/notifier/dist
    - name: Install CapRover
      run: npm install -g caprover
    - name: Zip aftifact into .tar file
      uses: thedoctor0/zip-release@master
      with:
        type: 'tar'
        filename: 'output.tar'
        path: 'backend/notifier/dist'
    - name: Push artifact to private Odzi Platform instance
      run: |
        ls
        caprover deploy -h https://captain.app.odzi.dog -p ${{ secrets.CAPROVER_PASSWORD }} -t output.tar -a pawcapsu-notifier